# docker-compose build --no-cache
# docker-compose up --force-recreate

version: '3'

services:
  redis:
    image: redis:5.0
    expose:
      - ${REDIS_PORT:-6379}
    command: ['redis-server', '--appendonly', 'yes', '--requirepass', '${REDIS_PASSWORD:-123456}']

  postgresql:
    image: postgres:14.5
    expose:
      - ${POSTGRES_PORT:-5432}
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-123456}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/

  syncbyte-remote-worker:
    image: syncbyte-py:latest
    depends_on:
      - redis
    environment:
      - DATABASE_URI=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-123456}@postgresql:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      - REDIS_URI=redis://:${REDIS_PASSWORD:-123456}@redis:${REDIS_PORT:-6379}/${REDIS_DB:-0}
      - HOST_PATH=${HOST_PATH}
    volumes:
      - ${HOST_PATH}:/var/run/syncbyte:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/local/bin/docker
    command: /opt/venv/bin/celery -A app.celery.app worker -P threads -c 64 -Q remote_q -l debug

  syncbyte-default-worker:
    image: syncbyte-py:latest
    depends_on:
      - postgresql
      - redis
    environment:
      - DATABASE_URI=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-123456}@postgresql:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      - REDIS_URI=redis://:${REDIS_PASSWORD:-123456}@redis:${REDIS_PORT:-6379}/${REDIS_DB:-0}
    command: /opt/venv/bin/celery -A app.celery.app worker -P threads -c 64 -Q default -l debug

  syncbyte-webapi:
    image: syncbyte-py:latest
    depends_on:
      - postgresql
      - redis
      - syncbyte-remote-worker
      - syncbyte-default-worker
    ports:
      - "${UVICORN_PORT:-8000}:8000"
    environment:
      - DATABASE_URI=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-123456}@postgresql:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      - REDIS_URI=redis://:${REDIS_PASSWORD:-123456}@redis:${REDIS_PORT:-6379}/${REDIS_DB:-0}
    command: /opt/venv/bin/python3 main.py run
