"""3

Revision ID: 80d7aa98ca72
Revises: ca8c4b92c218
Create Date: 2022-09-11 17:07:01.911487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d7aa98ca72'
down_revision = 'ca8c4b92c218'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('endpoint', sa.String(length=60), nullable=True),
    sa.Column('access_key', sa.String(length=200), nullable=True),
    sa.Column('secret_key', sa.String(length=200), nullable=True),
    sa.Column('bucket_name', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s3')
    # ### end Alembic commands ###
