"""2

Revision ID: ca8c4b92c218
Revises: 33abe6f320cc
Create Date: 2022-09-07 07:59:09.458105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8c4b92c218'
down_revision = '33abe6f320cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('db_type', sa.String(length=20), nullable=True))
    op.add_column('resource', sa.Column('db_version', sa.String(length=60), nullable=True))
    op.add_column('resource', sa.Column('host', sa.String(length=60), nullable=True))
    op.add_column('resource', sa.Column('port', sa.Integer(), nullable=True))
    op.add_column('resource', sa.Column('user', sa.String(length=60), nullable=True))
    op.add_column('resource', sa.Column('password', sa.String(length=500), nullable=True))
    op.add_column('resource', sa.Column('dbname', sa.String(length=100), nullable=True))
    op.add_column('resource', sa.Column('args', sa.String(length=600), nullable=True))
    op.drop_column('resource', 'uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('uri', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('resource', 'args')
    op.drop_column('resource', 'dbname')
    op.drop_column('resource', 'password')
    op.drop_column('resource', 'user')
    op.drop_column('resource', 'port')
    op.drop_column('resource', 'host')
    op.drop_column('resource', 'db_version')
    op.drop_column('resource', 'db_type')
    # ### end Alembic commands ###
